### ISSUE TITLE
Expose more config parameters

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/zeebe-cluster-helm#15]
In order to use the helm chart for our development and testing purposes we need to have more configuration options.

## Needed Configurations

I will collect in this issue configurations we need  and will create separate issues for each of them 

 - [X] Elasticsearch should be configurable (pvc size, max heap) https://github.com/zeebe-io/zeebe-cluster-helm/issues/10
 - [ ] Would be nice to enable/disable curator https://github.com/zeebe-io/zeebe-cluster-helm/issues/11
 - [X] Would be nice to enable/disable service monitor https://github.com/zeebe-io/zeebe-cluster-helm/issues/12
 - [X] more fine granulare zeebe statefulset configuration https://github.com/zeebe-io/zeebe-cluster-helm/issues/13
 - [ ] expose Zeebe configuration https://github.com/zeebe-io/zeebe-cluster-helm/issues/14
- [ ] standalone Gateway #1
